/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.dranke.math.trainer

import de.dranke.math.trainer.tasks.AdditionTaskFactory
import de.dranke.math.trainer.tasks.NumberGenerator

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val additionFactory = AdditionTaskFactory(NumberGenerator(), 50, 250)
    val taskCount: Int = when (args.count()) {
        1 -> (args[0].toIntOrNull().let {
            when (it) {
                null -> {
                    println("Value '${args[0]}' is not an Int."); 0
                }
                else -> it
            }
        })
        else -> {
            println("Amount of tasks is missing"); 0
        }
    }

    println("Taskcount: $taskCount")

    for (taskNumber in 1..taskCount) {
        println(additionFactory.createTask())
    }
}
